#!/bin/bash

commit=$(git log --color=always \
  --format="%C(green bold)%H%Creset %C(yellow)[%ad]%Creset %C(white bold)%s%Creset %Cblue[%an]%Creset" \
  --date=format:%Y-%m-%d | fzf --no-sort --ansi --multi)

if [[ -n "$commit" ]]; then
  commit_hash=$(echo "$commit" | awk '{print $1}')
  
  # Use pbcopy if available, otherwise use xclip
  if command -v pbcopy &> /dev/null; then
    echo "$commit_hash" | pbcopy
  elif command -v xclip &> /dev/null; then
    echo "$commit_hash" | xclip -selection clipboard
  else
    echo "No clipboard utility found. Please install pbcopy or xclip."
    exit 1
  fi

  git --no-pager show --pretty=medium -s --color=always "$commit_hash"
fi
