#!/bin/bash
repo_cache_path="${HOME}/.github_repo_cache"
selected_repo_url=$(awk '{print sprintf("https://github.com/%s", $1)}' $repo_cache_path | dmenu -l 20 -c)

if ! [[ -z $selected_repo_url ]]; then
  chromium $selected_repo_url
fi
