#!/bin/ruby

require "open3"

input = ARGF.read

indented, status_indent =
  Open3.capture2(
    "python3 -c 'import sys,textwrap; print(textwrap.dedent(sys.stdin.read()))'",
    stdin_data: input
  )

output, status_clipboard =
  Open3.capture2("xsel --clipboard --input", stdin_data: <<~DATA)
```ruby
#{indented.chomp}```
DATA

puts input
