#!/bin/bash

xloc=$(xdotool getmouselocation --shell | grep X | awk '{split($0,a,"="); print a[2]}')

if [[ $xloc -gt 3840 ]]; then
  xdotool mousemove 2000 2500
else
  xdotool mousemove 5000 2000
fi
